"""The connector's own face as a 2D outline with its pin holes, for the generic emblem on the flange (emblem = "nacs").
Sections Tesla's housing mesh (reference/nacs-500v-connector-housing.stl, from the official STEP) 0.5 mm behind the
nose tip and writes nacs_face.scad: nacs_face_outer (the outline) and nacs_face_holes (the pin holes), in mm,
across = x, up = y (the lock pocket side down), centred on the outline's bounding box.

    .venv/bin/python projects/NACS-wall-holder/pipeline/nacs_face.py
"""
import os

import numpy as np
import trimesh

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
m = trimesh.load(f"{PROJECT}/reference/nacs-500v-connector-housing.stl")
AX = int(np.argmax(m.extents))          # the housing's long axis; the nose tip is at its low end


def section(x):
    o = np.zeros(3); o[AX] = x
    n = np.zeros(3); n[AX] = 1
    s = m.section(plane_origin=o, plane_normal=n)
    p2, T = s.to_2D()
    # back to the mesh frame: the two in-plane axes are the other two of (x, y, z)
    axes = [i for i in range(3) if i != AX]
    polys = []
    for poly in sorted(p2.polygons_full, key=lambda q: -q.area):     # largest first: the housing's outline, then pins and ribs
        def back(coords):
            c = np.array(coords)
            h = np.c_[c, np.zeros(len(c)), np.ones(len(c))] @ T.T
            return h[:, axes]
        polys.append((back(poly.exterior.coords), [back(i.coords) for i in poly.interiors]))
    return polys


face = section(m.bounds[0][AX] + 0.5)
outer, holes = face[0]
# which way is up: the face is wider near its top than near its bottom; compare with nose_outline.scad, whose lowest line is the lock pocket side
import re
no = np.array(eval(re.search(r"nose_outline\s*=\s*(\[.*?\]);", open(f"{PROJECT}/nose_outline.scad").read(), re.S).group(1)))
def width_ratio(o):                     # width at 3/4 height over width at 1/4 height
    lo, hi = o[:, 1].min(), o[:, 1].max()
    w = lambda y: np.ptp(o[np.abs(o[:, 1] - y) < 1.5][:, 0])
    return w(lo + 0.75 * (hi - lo)) / w(lo + 0.25 * (hi - lo))
sign = 1 if (width_ratio(outer) > 1) == (width_ratio(no) > 1) else -1
print(f"width ratio top/bottom: face {width_ratio(outer):.2f}, nose_outline {width_ratio(no):.2f} -> up = {'+y' if sign > 0 else '-y'} of the mesh")
area = lambda h: abs(sum(h[i, 0] * h[i + 1, 1] - h[i + 1, 0] * h[i, 1] for i in range(len(h) - 1)) / 2)


def fmt(pts, ctr):
    pts = np.array([[p[0] - ctr[0], sign * (p[1] - ctr[1])] for p in pts])
    return "[" + ", ".join(f"[{x:.2f}, {y:.2f}]" for x, y in pts) + "]"


ctr = (outer[:, 0].min() + outer[:, 0].max()) / 2, (outer[:, 1].min() + outer[:, 1].max()) / 2
with open(f"{PROJECT}/nacs_face.scad", "w") as f:
    f.write("// GENERATED by pipeline/nacs_face.py: the NACS connector's face 0.5 mm behind the nose tip, from Tesla's housing STEP.\n")
    f.write(f"// Outline {np.ptp(outer[:, 0]):.1f} across x {np.ptp(outer[:, 1]):.1f} up, {len(holes)} pin holes; across = x, up = y, lock pocket side down.\n")
    f.write(f"nacs_face_outer = {fmt(outer, ctr)};\n")
    f.write("nacs_face_holes = [" + ", ".join(fmt(h, ctr) for h in holes) + "];\n")
print(f"outline {np.ptp(outer[:, 0]):.1f} x {np.ptp(outer[:, 1]):.1f}, {len(holes)} holes, areas {[round(area(h), 1) for h in holes]}")
